[model]
package = "bonito.crf"

[labels]
labels = [ "N", "A", "C", "G", "T",]

[input]
features = 1

[qscore]
bias = -1.635
scale = 0.8529

[encoder]
stride = 5
winlen = 19
scale = 5.0
features = 128
rnn_type = "lstm"
activation = "swish"
blank_score = 2.0

[global_norm]
state_len = 3

[basecaller]
batchsize = 1536
chunksize = 10000
overlap = 500
quantize = false
